In [14]:
import torch

In [15]:
p = torch.Tensor([i + 1 for i in range(24)])

In [16]:
p.view(4,3,2), p.view(4,2,3)

(tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [11., 12.]],
 
         [[13., 14.],
          [15., 16.],
          [17., 18.]],
 
         [[19., 20.],
          [21., 22.],
          [23., 24.]]]),
 tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]],
 
         [[13., 14., 15.],
          [16., 17., 18.]],
 
         [[19., 20., 21.],
          [22., 23., 24.]]]))

In [20]:
a = p.view(2,2,3,2).transpose(1, 3)
p.view(2,2,3,2), a

(tensor([[[[ 1.,  2.],
           [ 3.,  4.],
           [ 5.,  6.]],
 
          [[ 7.,  8.],
           [ 9., 10.],
           [11., 12.]]],
 
 
         [[[13., 14.],
           [15., 16.],
           [17., 18.]],
 
          [[19., 20.],
           [21., 22.],
           [23., 24.]]]]),
 tensor([[[[ 1.,  7.],
           [ 3.,  9.],
           [ 5., 11.]],
 
          [[ 2.,  8.],
           [ 4., 10.],
           [ 6., 12.]]],
 
 
         [[[13., 19.],
           [15., 21.],
           [17., 23.]],
 
          [[14., 20.],
           [16., 22.],
           [18., 24.]]]]))